export let currency_list = [
    { ccy: "AED", tag: "AE" },
    { ccy: "AFN", tag: "AF" },
    { ccy: "XCD", tag: "AG" },
    { ccy: "ALL", tag: "AL" },
    { ccy: "AMD", tag: "AM" },
    { ccy: "ANG", tag: "AN" },
    { ccy: "AOA", tag: "AO" },
    { ccy: "AQD", tag: "AQ" },
    { ccy: "ARS", tag: "AR" },
    { ccy: "AUD", tag: "AU" },
    { ccy: "AZN", tag: "AZ" },
    { ccy: "BAM", tag: "BA" },
    { ccy: "BBD", tag: "BB" },
    { ccy: "BDT", tag: "BD" },
    { ccy: "XOF", tag: "BE" },
    { ccy: "BGN", tag: "BG" },
    { ccy: "BHD", tag: "BH" },
    { ccy: "BIF", tag: "BI" },
    { ccy: "BMD", tag: "BM" },
    { ccy: "BOB", tag: "BO" },
    { ccy: "BRL", tag: "BR" },
    { ccy: "BSD", tag: "BS" },
    { ccy: "NOK", tag: "BV" },
    { ccy: "BWP", tag: "BW" },
    { ccy: "BYR", tag: "BY" },
    { ccy: "BZD", tag: "BZ" },
    { ccy: "CAD", tag: "CA" },
    { ccy: "CDF", tag: "CD" },
    { ccy: "XAF", tag: "CF" },
    { ccy: "CHF", tag: "CH" },
    { ccy: "CLP", tag: "CL" },
    { ccy: "CNY", tag: "CN" },
    { ccy: "COP", tag: "CO" },
    { ccy: "CRC", tag: "CR" },
    { ccy: "CUP", tag: "CU" },
    { ccy: "CVE", tag: "CV" },
    { ccy: "CYP", tag: "CY" },
    { ccy: "CZK", tag: "CZ" },
    { ccy: "DJF", tag: "DJ" },
    { ccy: "DKK", tag: "DK" },
    { ccy: "DOP", tag: "DO" },
    { ccy: "DZD", tag: "DZ" },
    { ccy: "ECS", tag: "EC" },
    { ccy: "EEK", tag: "EE" },
    { ccy: "EGP", tag: "EG" },
    { ccy: "EUR", tag: "FR" },
    { ccy: "ETB", tag: "ET" },
    { ccy: "FJD", tag: "FJ" },
    { ccy: "FKP", tag: "FK" },
    { ccy: "GBP", tag: "GB" },
    { ccy: "GEL", tag: "GE" },
    { ccy: "GGP", tag: "GG" },
    { ccy: "GHS", tag: "GH" },
    { ccy: "GIP", tag: "GI" },
    { ccy: "GMD", tag: "GM" },
    { ccy: "GNF", tag: "GN" },
    { ccy: "GTQ", tag: "GT" },
    { ccy: "GYD", tag: "GY" },
    { ccy: "HKD", tag: "HK" },
    { ccy: "HNL", tag: "HN" },
    { ccy: "HRK", tag: "HR" },
    { ccy: "HTG", tag: "HT" },
    { ccy: "HUF", tag: "HU" },
    { ccy: "IDR", tag: "ID" },
    { ccy: "ILS", tag: "IL" },
    { ccy: "INR", tag: "IN" },
    { ccy: "IQD", tag: "IQ" },
    { ccy: "IRR", tag: "IR" },
    { ccy: "UAH", tag: "UA" },
    { ccy: "UGX", tag: "UG" },
    { ccy: "USD", tag: "US" },
    // "USD" : "US",
    // "ISK" : "IS",
    // "JMD" : "JM",
    // "JOD" : "JO",
    // "JPY" : "JP",
    // "KES" : "KE",
    // "KGS" : "KG",
    // "KHR" : "KH",
    // "KMF" : "KM",
    // "KPW" : "KP",
    // "KRW" : "KR",
    // "KWD" : "KW",
    // "KYD" : "KY",
    // "KZT" : "KZ",
    // "LAK" : "LA",
    // "LBP" : "LB",
    // "LKR" : "LK",
    // "LRD" : "LR",
    // "LSL" : "LS",
    // "LTL" : "LT",
    // "LVL" : "LV",
    // "LYD" : "LY",
    // "MAD" : "MA",
    // "MDL" : "MD",
    // "MGA" : "MG",
    // "MKD" : "MK",
    // "MMK" : "MM",
    // "MNT" : "MN",
    // "MOP" : "MO",
    // "MRO" : "MR",
    // "MTL" : "MT",
    // "MUR" : "MU",
    // "MVR" : "MV",
    // "MWK" : "MW",
    // "MXN" : "MX",
    // "MYR" : "MY",
    // "MZN" : "MZ",
    // "NAD" : "NA",
    // "XPF" : "NC",
    // "NGN" : "NG",
    // "NIO" : "NI",
    // "NPR" : "NP",
    // "NZD" : "NZ",
    // "OMR" : "OM",
    // "PAB" : "PA",
    // "PEN" : "PE",
    // "PGK" : "PG",
    // "PHP" : "PH",
    // "PKR" : "PK",
    // "PLN" : "PL",
    // "PYG" : "PY",
    // "QAR" : "QA",
    // "RON" : "RO",
    // "RSD" : "RS",
    // "RUB" : "RU",
    // "RWF" : "RW",
    // "SAR" : "SA",
    // "SBD" : "SB",
    // "SCR" : "SC",
    // "SDG" : "SD",
    // "SEK" : "SE",
    // "SGD" : "SG",
    // "SKK" : "SK",
    // "SLL" : "SL",
    // "SOS" : "SO",
    // "SRD" : "SR",
    // "STD" : "ST",
    // "SVC" : "SV",
    // "SYP" : "SY",
    // "SZL" : "SZ",
    // "THB" : "TH",
    // "TJS" : "TJ",
    // "TMT" : "TM",
    // "TND" : "TN",
    // "TOP" : "TO",
    // "TRY" : "TR",
    // "TTD" : "TT",
    // "TWD" : "TW",
    // "TZS" : "TZ",
    // "UYU" : "UY",
    // "UZS" : "UZ",
    // "VEF" : "VE",
    // "VND" : "VN",
    // "VUV" : "VU",
    // "YER" : "YE",
    // "ZAR" : "ZA",
    // "ZMK" : "ZM",
    // "ZWD" : "ZW"
]